"""empty message

Revision ID: 2fc6ec339cda
Revises: 93c6ed34af5d
Create Date: 2025-08-29 20:22:26.598514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc6ec339cda'
down_revision = '93c6ed34af5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visited',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('poi_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'poi_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visited')
    # ### end Alembic commands ###
