"""empty message

Revision ID: 93c6ed34af5d
Revises: aa039f163d08
Create Date: 2025-08-29 10:01:03.221221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c6ed34af5d'
down_revision = 'aa039f163d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_image',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=240), nullable=False),
    sa.Column('poi_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('poi_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=240), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.VARCHAR(length=240), autoincrement=False, nullable=False))

    op.drop_table('tag')
    op.drop_table('poi_image')
    # ### end Alembic commands ###
