"""empty message

Revision ID: f47374ccd87e
Revises: ca0902f0cc6f
Create Date: 2025-09-03 00:29:48.962445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47374ccd87e'
down_revision = 'ca0902f0cc6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_city_name_country', ['name', 'country_id'])

    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_poi_name_city', ['name', 'city_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.drop_constraint('uq_poi_name_city', type_='unique')

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_constraint('uq_city_name_country', type_='unique')

    # ### end Alembic commands ###
